### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by andykais** [cmdr2/stable-diffusion-ui#1069]
**Is your feature request related to a problem? Please describe.**
generally when I save settings I want to keep them on forever, but they are specific to the web browser and machine I open the webpage on.

**Describe the solution you'd like**
Ideally we would have a config file where settings can also be read from. Essentially the "defaults" would exist in the config file, and they would be overridden by the browser settings. E.g.
```yaml
save_images: true
save_metadata: true
metadata_format: 'json'
save_folder: '/path/to/my/save/dir'
```

**Describe alternatives you've considered**
I have considered hardcoding the settings that I care about inside the repo, or creating a proxy server that sits on top of the server to pass the config I care about

**Additional context**
I start and stop the stable-diffusion-ui process so that it is only on when I am using it, and relying on config in local storage feels much more brittle than a universal config file.
