### ISSUE TITLE
ERR_EMPTY_RESPONSE on port 9000

### ISSUE THREAD

**Issue by ChrisAcrobat** [cmdr2/stable-diffusion-ui#16]
I can't reach the UI after update. Port 8000 works fine, it displays the rodiet notice, but port 9000 returns nothing at all.
I'm running Windows, so I was not (easily) able to execute the `server` file. But I opened it and executed the code below (`start_server()`) as a troubleshoot. Without luck though.
```
docker-compose up -d stable-diffusion-old-port-redirect
docker-compose up stability-ai stable-diffusion-ui
```

**Comment by cmdr2** [comment]
Hi @ChrisAcrobat , I'm rolling back the server script, since I'm really not sure why it is causing problems. b860dbd9a6d36f645a5406076d9d30ecf33bbad2

I will investigate this further.

I looked at your PR, thanks!

Can you please try the latest version and let me know if it still causes problems? Are you able to see the redirect notice at http://localhost:8000 and the actual UI at http://localhost:9000 ?

Thanks

**Comment by ChrisAcrobat** [comment]
I made an reinstall, but no.
What I think the problem is that the internal server still uses port 8000, that's why I changed the external port (9000) to redirect to the old internal port (8000) with #17. The change fixed my problem, but I not sure if that is a permanent or temporarily solution. Can it still lead to port conflicts? Was ages ago I read about Dockers internal network because I had a problem that I was trying to solve (but didn't 🙂).

**Comment by cmdr2** [comment]
Thanks, one last try. Can you please update your `docker-compose.yml` to this, and run `docker-compose up` and then `docker-compose up &` ?

I suspect the old docker image (which started the main UI server at port 8000) is still being used. I've changed the service name, so it'll be forced to create a new image for it. Thanks!

```
version: '3.3'

services:
  stability-ai-v2:
    container_name: sd
    ports:
      - '5000:5000'
    image: 'r8.im/stability-ai/stable-diffusion@sha256:be04660a5b93ef2aff61e3668dedb4cbeb14941e62a3fd5998364a32d613e35e'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  stable-diffusion-ui-v2:
    container_name: sd-ui
    ports:
      - '9000:9000'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - stability-ai

  stable-diffusion-old-port-redirect-v2:
    container_name: sd-old-port-redirect
    ports:
      - '8000:8000'
    build:
      context: .
      dockerfile: OldPortDockerfile
    volumes:
      - .:/app

networks:
  default:
```
